var song_of_solomon_data = {
  "chapter_1": {
    "verse_1": "This is Solomon's most beautiful song.",
    "verse_2": "Please kiss me with your lips! Your love makes me happier than wine does.",
    "verse_3": "You have put perfume on your body. It has a lovely smell. The sound of your name causes pleasure everywhere, like sweet perfume. All the young women love you!",
    "verse_4": "Take me away with you. Come quickly. I want the king to take me into his rooms. We are very happy! You make us happy. We praise your love, because it is better than wine. I agree! The young women are right to praise you like that.",
    "verse_5": "Young women of Jerusalem, my skin is dark but I am beautiful. My skin is dark, like the tents of Kedar. It is beautiful, like the curtains of King Solomon's tent.",
    "verse_6": "The sun has caused my skin to become dark. Please do not look at me as if I am strange. My brothers were angry with me. They caused me to work outside in the sun. I took care of the vineyards, and I could not take care of my own vineyard, my body.",
    "verse_7": "I love you, my dear one. Tell me where you take your sheep to eat grass. Where will you take them to rest at midday? I do not want to look for you everywhere among the sheep of your friends. They might not understand what I am doing.",
    "verse_8": "You are the most beautiful woman of all. If you do not know where to find me, follow the marks from the feet of my sheep. Take your young goats to eat grass among the tents of the shepherds.",
    "verse_9": "My dear friend, you are very beautiful. You seem to me like a beautiful horse that pulls one of Pharaoh's chariots.",
    "verse_10": "Your face is beautiful with jewels. A necklace makes your neck beautiful too.",
    "verse_11": "We will use gold to make ear rings for you, and we will add pieces of silver.",
    "verse_12": "While the king was eating a meal, the sweet smell of my perfume was in the air.",
    "verse_13": "My lover is like a bag of myrrh that lies between my breasts.",
    "verse_14": "He is like a group of henna flowers that grow in the vineyards at En Gedi.",
    "verse_15": "My dear friend, I see that you are very beautiful! Yes, you are beautiful and your eyes are like doves.",
    "verse_16": "My lover, I see that you are very handsome! Yes, you are lovely! This field of fresh, green grass is our comfortable bed.",
    "verse_17": "The cedar trees above us are the beams of our bedroom. The pine trees cover us like a roof."
  },
  "chapter_2": {
    "verse_1": "I am a wild flower of Sharon. I am a lily from the valleys.",
    "verse_2": "Among the other young women, my dear friend is like a lily that grows among thorn bushes.",
    "verse_3": "Among the other young men, my lover is like an apple tree that grows among the trees of the forest. I love to sit in his shade. His fruit is sweet when I taste it.",
    "verse_4": "He has taken me to the room for feasts. Everyone can see that he loves me.",
    "verse_5": "I am weak with love. So give me raisins to make me strong. Give me apples to me to keep me awake.",
    "verse_6": "His left hand is under my head. His right hand brings me near to him.",
    "verse_7": "Promise this to me, young women of Jerusalem: Do not cause our love to wake up. Do not cause it to become too strong until the time is right. The gazelles and the wild deer will know about your promise.",
    "verse_8": "Listen! I hear the voice of my lover! Look! He is coming! He moves quickly across the mountains. He runs across the hills.",
    "verse_9": "My lover is like a gazelle or a young male deer. Look! There he is! He is standing behind our wall. He is looking through the window. He wants to see into the room.",
    "verse_10": "My lover said this to me: ‘My beautiful friend, I love you. Get up now and come with me.",
    "verse_11": "Look! The winter time has finished. The heavy rains have stopped.",
    "verse_12": "Flowers are appearing everywhere. It is now the season to sing happy songs. We can hear the voices of doves around us.",
    "verse_13": "New fruit is growing on the fig trees. There are flowers on the vines, and their sweet smell is in the air. I love you, my beautiful friend. Please get up now and come with me!’",
    "verse_14": "My dear friend, you are like a dove that is hiding among the rocks. You hide from me in the mountains. Show your face to me because it is lovely. Let me hear your voice because it has a sweet sound.",
    "verse_15": "Catch the foxes for us! Our vines now have flowers and they will soon give us fruit. So catch the little foxes before they destroy our vineyards.",
    "verse_16": "My lover belongs to me, and I belong to him. He moves among the lilies with his sheep.",
    "verse_17": "Turn back to me, my lover. Stay until dawn comes and the shadows have gone, Be like a gazelle or a young male deer that plays among the mountains' rocks."
  },
  "chapter_3": {
    "verse_1": "All night I lay on my bed. I wanted my lover to come to me. I looked for him but he did not appear.",
    "verse_2": "I thought, ‘I will get up now and I will go into the city. I will look everywhere for my lover. I will look in all the streets. I will look in all the market places.’ So I looked for him, but I did not find him.",
    "verse_3": "The city guards found me as they walked in the streets of the city. I asked them, ‘Have you seen the man that I love?’",
    "verse_4": "Just then, as I left them, I found my lover! I hugged him and I would not let him go. I took him to my mother's house. I took him into my mother's bedroom. That is where my life started, inside my mother's body.",
    "verse_5": "Promise this to me, young women of Jerusalem: Do not cause our love to wake up. Do not cause it to become too strong until the time is right. The gazelles and the wild deer will know about your promise.",
    "verse_6": "Who is this who is coming from the desert? It seems that smoke is rising into the air! There is a lovely smell of myrrh and incense. It is the smell of all the spices that a trader sells.",
    "verse_7": "Look! They are carrying King Solomon on a throne! 60 soldiers are travelling with it. They are Israel's bravest soldiers.",
    "verse_8": "All of them have swords. They all know how to fight well. Their swords are ready for them to use. They are ready for any danger that comes in the night.",
    "verse_9": "King Solomon made the throne for himself. He used wood from Lebanon to make it.",
    "verse_10": "He used silver to make the posts for it. He used gold to make its back. Its seat has valuable purple cloth to cover it. The young women of Jerusalem made it beautiful inside, to show their love.",
    "verse_11": "Young women of Zion, come out to see King Solomon! He is wearing his crown. His mother put the crown on him on his wedding day. It was the happiest day of his life!"
  },
  "chapter_4": {
    "verse_1": "My dear friend, how beautiful you are! Yes, you are very beautiful! Your eyes behind your veil are like doves. Your hair is like a group of goats that are coming down from Mount Gilead.",
    "verse_2": "Your teeth are very white like a group of sheep. They are like sheep after someone has cut off their dirty wool and they are coming from the pool of water. Each tooth is one of a pair. Not one of them is alone.",
    "verse_3": "Your lips are like bright red strings. Your mouth is lovely. The sides of your face are beautiful, like the halves of a pomegranate. I see them through your veil.",
    "verse_4": "Your neck is like the great tower of King David. It is round and strong. Your necklace is like the shields of 1,000 brave soldiers that hang from the stones of the tower.",
    "verse_5": "Your breasts are perfect, like two young gazelles that are twins. They feed themselves among the lilies.",
    "verse_6": "I will go to the mountain of myrrh and the hill of frankincense. I will stay among them until the dawn comes and the shadows go away.",
    "verse_7": "You are completely beautiful, my dear friend. Your body is perfect in every way.",
    "verse_8": "Come with me from Lebanon, my bride. Yes, come with me from Lebanon. Come down from the top of Amana, from the top of Senir. Come down from the highest part of Hermon. Come away from those mountains where lions live, and where there are leopards.",
    "verse_9": "I love you so much that I never want to leave you, my sister and my bride. When you looked at me only once and I saw one jewel in your necklace, I knew that I could never leave you.",
    "verse_10": "Your love for me is wonderful, my sister and my bride. I enjoy your love even more than I enjoy wine. Your perfume has a smell that is more lovely than any spice!",
    "verse_11": "Your lips taste very sweet to me, my bride. They taste like honey that falls from the honeycomb. Milk and honey are under your tongue. The smell of your clothes is like the cedar trees of Lebanon.",
    "verse_12": "My sister and my bride, you are like a garden for me that is locked to other men. You are like a spring or a fountain that other people may not drink water from.",
    "verse_13": "Your body is like a special garden. It is full of pomegranate trees with their sweet fruit. There are wonderful fruits to enjoy. There are also henna and nard.",
    "verse_14": "There are nard, saffron, calamus, cinnamon and many different spices. There are myrrh, aloes and all the best spices.",
    "verse_15": "You are like a spring of water in a garden. You are like a well that has fresh water. The water runs down from Lebanon's mountains.",
    "verse_16": "Wake up, north wind! Come now, south wind! Blow on my garden! Make the sweet smell of its spices move in the air. May my lover come into his garden now! Let him taste its wonderful fruits!"
  },
  "chapter_5": {
    "verse_1": "I have come into my garden, my sister, my bride. I have taken my myrrh with my spice. I have eaten my honeycomb and my honey. I have drunk my wine and my milk. Eat, friends, and drink, you who love each other! Drink until you can drink no more!",
    "verse_2": "I slept but my mind was awake. Listen! My lover is knocking on my door! He said, ‘Open the door for me, my dear friend. You are my sister, the perfect one that I love. To me you are like a beautiful dove. Dew from the night air covers my head. My hair is very wet.’",
    "verse_3": "I said, ‘I have taken off my day clothes. I do not want to dress myself again. I have washed my feet. I do not want them to get dirty again.’",
    "verse_4": "My lover pushed his hand through the hole in the door. My heart began to beat faster because he was near.",
    "verse_5": "I got up to open the door for my lover. My hands were wet with myrrh. Myrrh dropped from my fingers onto the handle of the door.",
    "verse_6": "I opened the door for my lover. But he had already turned away. He had gone! I was very upset that he had gone away. I looked for him but I did not find him. I called to him but he did not answer me.",
    "verse_7": "The city guards found me as they walked in the streets of the city. They beat me and they hurt my body. Those guards on the city walls took away my robe.",
    "verse_8": "Young women of Jerusalem, please find my lover! Promise me to tell him this, if you find him. Tell him that my love for him has made me weak!",
    "verse_9": "Tell us this, most beautiful of all women. Why do you think that your lover is better than other men? Why must we promise to do this for you?",
    "verse_10": "My lover is very handsome and healthy. He is the greatest man among 10,000 men.",
    "verse_11": "His head is like very pure gold. The hairs on his head are like waves. They are black like a raven.",
    "verse_12": "His eyes are like doves beside streams of water. They are like doves that someone has washed in milk. They shine like jewels.",
    "verse_13": "The sides of his face are like a garden with spice trees. Their smell is like perfume. His lips are like lilies with myrrh that falls from them.",
    "verse_14": "His arms are like bars of gold with jewels in them. His body shines like bright ivory, with sapphire jewels to make it more beautiful.",
    "verse_15": "His legs are like pillars of beautiful stone. They stand on feet that are like pure gold. He stands tall like the mountains of Lebanon. He is as handsome as its best cedar trees.",
    "verse_16": "The taste of his mouth is very sweet. Everything about him causes me to love him. I say to you, young women of Jerusalem, this is my lover! This is my true friend."
  },
  "chapter_6": {
    "verse_1": "Tell us this, most beautiful of all women. Where has your lover gone? Which way did he go? Tell us, so that we can look for him with you.",
    "verse_2": "My lover has gone down to his garden. He has gone to his garden of spice trees. He has gone there to walk in the gardens and to pick lilies.",
    "verse_3": "My lover belongs to me, and I belong to him. He moves among the lilies with his sheep.",
    "verse_4": "My dear friend, you are as beautiful as Tirzah. You are as lovely as Jerusalem. You are as wonderful as an army that is waving its flags.",
    "verse_5": "Turn your eyes away from me. They give me pleasure that is too strong for me! Your hair is like a group of goats that are coming down from Mount Gilead.",
    "verse_6": "Your teeth are very white like a group of clean sheep that is coming from the pool of water. Each tooth is one of a pair. Not one of them is alone.",
    "verse_7": "The sides of your face are beautiful, like the halves of a pomegranate. I see them through your veil.",
    "verse_8": "A king may have 60 queens. He may have 80 slave wives. He may have many other young women too. There may be too many for him to count!",
    "verse_9": "But there is only one woman that I want. Nobody is like her in any way. She is my perfect one, as lovely as a dove. She is the special daughter of her mother. Her mother loves her best among all her children. The young women saw her and they praised her. The queens and the slave wives also praised her.",
    "verse_10": "They said, ‘She is like the light that appears at dawn. She is as beautiful as the moon. She is as bright as the sun. She is as wonderful as the stars that shine brightly in their places.’",
    "verse_11": "I went down to the garden of walnut trees. I wanted to see the new plants that were growing in the valley; to see if the vines had new leaves now; to see if the pomegranate trees had flowers.",
    "verse_12": "I became so happy that I did not understand what was happening. I knew that I wanted to be with her. I felt that I was riding with the king's men in their chariots.",
    "verse_13": "Come back, come back, young woman from Shulam! Yes, come back, so that we can look at you again. Why do you want to look at the young woman from Shulam? Do not look at her as if she is dancing the dance of Mahanaim."
  },
  "chapter_7": {
    "verse_1": "How beautiful are your feet in sandals, my princess! Your round hips are as beautiful as jewels that a clever worker has made.",
    "verse_2": "Your navel is like a round bowl that is always full of good wine. Your stomach is like a round heap of wheat with lilies around the edge.",
    "verse_3": "Your breasts are like two young gazelles that are twins.",
    "verse_4": "Your neck is like an ivory tower. Your eyes shine like the pools in Heshbon that are near the Bath Rabbim gate. Your nose is like the tower of Lebanon that looks towards Damascus.",
    "verse_5": "Your head stands tall on you, like Mount Carmel. Your long hair hangs down like a royal cloth. It is so beautiful that it can make the king its prisoner!",
    "verse_6": "You are very beautiful, my dear friend, and I love you. You give a lot of pleasure to me.",
    "verse_7": "You stand like a tall palm tree. Your breasts are like bunches of fruit that hang from the tree.",
    "verse_8": "I said, ‘I will climb the palm tree. I will take hold of its fruit.’ For me, your breasts are like bunches of grapes. Your breath is like the sweet smell of apples.",
    "verse_9": "For me, your mouth has the taste of the best wine. May the wine pour out for my lover. May it pour over his lips and his teeth.",
    "verse_10": "I belong to my lover, and he wants to be with me!",
    "verse_11": "Come with me now, my lover! Let us go and walk through the fields. We can stay in the villages for the night.",
    "verse_12": "We can get up early in the morning and go to the vineyards. We can see if the vines have started to make new leaves. We can see if their flowers have opened. We can see if the pomegranate trees have flowers. When we are there I will give my love to you.",
    "verse_13": "The mandrake plants send out their sweet smell. At our door, there are many good things to eat. I have stored many good things that are both old and new. I have kept them all for you, my lover."
  },
  "chapter_8": {
    "verse_1": "I would like it if you were my brother who drank milk from my mother's breasts! If you were my brother, if I found you outside, I could kiss you. Nobody would think that I was doing something wrong.",
    "verse_2": "I would lead you to my mother's house. She is the one who has taught me. I would give you wine with spices to drink, the juice from my pomegranates.",
    "verse_3": "His left hand is under my head. His right hand brings me near to him.",
    "verse_4": "Promise this to me, young women of Jerusalem: Do not cause our love to wake up. Do not cause it to become too strong until the time is right.",
    "verse_5": "Who is this who is coming from the desert? Her head is on her lover's shoulder. Under the apple tree, I caused your love to wake. That is the place where your mother became pregnant. In that place too, your mother gave birth to you in pain.",
    "verse_6": "Keep me near to you, like a seal over your heart. Keep me like a seal on your arm. Keep me there always, because love is as powerful as death. It keeps hold of people as strongly as the grave does. Love burns like a hot fire. It burns with bright flames.",
    "verse_7": "Even a flood of water cannot stop the flames. Rivers of water cannot carry it away. A man might try to give all his riches to buy a woman's love. But she would refuse to accept what he offers to her.",
    "verse_8": "We have a younger sister. Her breasts have not yet grown. What will we do to help her when it is the time for her to marry?",
    "verse_9": "If she is a wall, we will use silver to build towers on her. But if she is a door, we will use boards of cedar wood to keep the door shut.",
    "verse_10": "I am a wall. My breasts are like strong towers. So my lover is happy when he looks at me.",
    "verse_11": "King Solomon had a vineyard in Baal Hamon. He allowed other people to take care of it. They each paid him 1,000 silver coins for its fruit.",
    "verse_12": "But my own vineyard belongs to me alone. I take care of it myself. You may keep the 1,000 silver coins, Solomon. And I will give 200 silver coins to those who take care of the fruit.",
    "verse_13": "You have been staying in the garden with your friends who are listening to you. Let me too hear your voice!",
    "verse_14": "Come quickly to me now, my lover! Run like a gazelle or a young deer. Come to the mountains that have sweet spices!"
  }
};
