var zechariah_data = {
  "chapter_1": {
    "verse_1": "When Darius had been king of Persia for two years, Zechariah the prophet heard a message from the Lord. It was the eighth month of the year. Zechariah was the son of Berekiah, and Berekiah was the son of Iddo.",
    "verse_2": "This was the Lord's message: ‘I, the Lord, was very angry with your ancestors.",
    "verse_3": "Now I, the Lord Almighty, say this to you: “If you return to me, I will return to you.”",
    "verse_4": "Do not be like your ancestors. Many years ago the prophets gave them a message from me. The message was, “Stop doing those evil and wicked things.” But they did not listen to me. They did not think that my message was important.",
    "verse_5": "That was a long time ago. Your ancestors have been dead for a long time. So have the prophets.",
    "verse_6": "I told my prophets to speak my message and my commands. I punished your ancestors, as I warned them I would do. Then they turned back to me. They said, “The Lord Almighty has punished us for our sins, as he said he would do.” ’",
    "verse_7": "On the 24th day of Shebat, the 11th month of the year, the Lord spoke to Zechariah the prophet. This was when Darius had been king for two years.",
    "verse_8": "During the night I, Zechariah, had a dream from the Lord. I saw a man on a red horse. The horse was standing among some trees called myrtle trees, in the valley. And behind him were red, brown and white horses.",
    "verse_9": "I asked him, ‘My lord, what are these horses?’ The angel who talked with me said, ‘I will show you what they are.’",
    "verse_10": "The man who was standing among the trees answered, ‘The Lord has sent these horses to go to all the places on the earth.’",
    "verse_11": "And the horses spoke to the angel of the Lord who stood among the trees. They said, ‘We have gone all over the earth. All the earth is without trouble.’",
    "verse_12": "Then the angel of the Lord said, ‘Lord Almighty, how long will you be angry with Jerusalem? How long will you be angry with the cities of Judah? You have already been angry for 70 years.’",
    "verse_13": "And the Lord answered the angel with kind words.",
    "verse_14": "The angel said to me, ‘Tell this to the people. This is what the Lord Almighty says: “I love Jerusalem. Jerusalem is mine.",
    "verse_15": "I am very angry with the countries that are safe and without danger. Those countries were too cruel to my people, when I was only a little angry with Jerusalem.”",
    "verse_16": "So this is what the Lord says: “I will return to Jerusalem to be kind to the people there. I will build my house again”, says the Lord Almighty, “and I will build the city again.” ’",
    "verse_17": "The angel told me that I must say this: ‘The Lord Almighty says, “My towns will be rich again. I will again speak kind words to Jerusalem. I will choose Jerusalem again as my own city.” ’",
    "verse_18": "And I looked up and I saw four horns.",
    "verse_19": "And I asked the angel that talked with me, ‘What are these horns?’ Then the angel said to me, ‘These are the strong enemies of my people. They took my people out of Judah, out of Israel and out of Jerusalem.’",
    "verse_20": "Then the Lord showed me four workers with hammers.",
    "verse_21": "I said, ‘What are these men coming to do?’ The Lord answered, ‘The horns are the enemies that destroyed Judah. They destroyed Judah and they made the people ashamed. The workers came to frighten and to destroy the enemies because they killed many of my people. The enemies took many of my people out of Judah.’"
  },
  "chapter_2": {
    "verse_1": "Then I looked up and I saw a man in front of me. He had a line in his hand. The line was to measure something.",
    "verse_2": "I asked the man, ‘Where are you going?’ He said to me, ‘I am going to measure Jerusalem. I want to see how wide and how long it is.’",
    "verse_3": "The angel that talked with me went away. Another angel came to meet him.",
    "verse_4": "The second angel said to the first angel, ‘Run to that young man with the line in his hand. Say that Jerusalem will be a city without walls. This is because of the many people and many animals that will live in it.",
    "verse_5": "The Lord himself promises that he will be like a wall of fire round Jerusalem. He will shine as a beautiful light inside the city.’",
    "verse_6": "‘Come! Come! Run away from the country in the north,’ says the Lord. ‘As the four winds blow in different directions, I sent you to many far countries.",
    "verse_7": "Come, my people. Run away from Babylon and return to Jerusalem.’",
    "verse_8": "Return because the Lord says, ‘Anyone that attacks you is attacking the Lord's people. He is attacking the people that the Lord loves.’ So the Lord Almighty sent me, Zechariah, with this message about the countries that have robbed his people.",
    "verse_9": "‘The Lord himself will fight against your enemies and their own slaves will rob them. Then you will know that the Lord Almighty has sent me, Zechariah, to you.’",
    "verse_10": "‘Sing and be happy, you people in Jerusalem. This is because I will come. And I will live among you,’ says the Lord.",
    "verse_11": "‘On that day, the people from many countries will come to me, the Lord, and they will become my people. I will live among you. You will know that the Lord Almighty has sent me.",
    "verse_12": "The Lord will choose Judah for himself again. Jerusalem will be the city that he loves most of all cities.",
    "verse_13": "Be quiet, all people, because the Lord has left his home in heaven to come among you.’"
  },
  "chapter_3": {
    "verse_1": "Then the angel of the Lord appeared to me, Zechariah, and he showed me Joshua, the most important priest. Joshua was standing in front of the angel of the Lord. Satan stood on the right side of Joshua. He was ready to say that Joshua had done bad things.",
    "verse_2": "The Lord said to Satan, ‘The Lord says that you are wrong. The Lord has chosen Jerusalem. And he says that you are wrong. Joshua is certainly like a burning stick that someone pulls quickly out of the fire.’",
    "verse_3": "Joshua was wearing very dirty clothes and he stood in front of the angel.",
    "verse_4": "The angel said to the other angels that stood in front of him, ‘Remove his very dirty clothes.’ Then the first angel said to Joshua, ‘See, I have taken away your sin. I will put the clothes on you that a priest should wear.’",
    "verse_5": "Then Zechariah said, ‘Put a clean hat on his head.’ So they put a clean hat on his head and they dressed him in clean clothes. The angel of the Lord stood near to them.",
    "verse_6": "The angel of the Lord spoke to Joshua with these serious words.",
    "verse_7": "‘These are the words of the Lord Almighty. Listen to them and obey them. “You will rule in my house. You will rule inside the walls of my house. I will give you a place among the angels that are standing here.",
    "verse_8": "Listen, Joshua, most important priest of the Lord. Listen you priests that sit with Joshua. You are like a sign. People can look at you. And they can know that good things will happen in future years. See! I will bring to you my servant who is called The Branch.",
    "verse_9": "See the stone that I have put in front of Joshua! It is a stone with seven sides and I will cut words in the stone”, says the Lord Almighty. “I will remove the sin of this country's people in one day.”",
    "verse_10": "“On that day”, says the Lord Almighty, “each of you will ask your friends to come. You will ask them to come and to sit under your own vines and fig trees.” ’"
  },
  "chapter_4": {
    "verse_1": "The angel that talked with me before woke me. I, Zechariah, was like a man who wakes out of his sleep.",
    "verse_2": "The angel said to me, ‘What do you see?’ I said, ‘I see a lampstand that is made from gold. It has seven lamps and a bowl on top which contains oil. And it has seven branches that take the oil to each lamp.",
    "verse_3": "And two olive trees are standing by the lampstand. One tree is on the right and one tree is on the left.’",
    "verse_4": "I, Zechariah, said to the angel that talked with me, ‘What does this light mean, my lord?’",
    "verse_5": "He said, ‘Do you not know what these are?’ I said, ‘No, my lord.’",
    "verse_6": "Then the angel said to me, ‘The Lord said this to Zerubbabel: “You will need my Spirit. You yourself are too weak. And you do not have enough power.” This is what the Lord Almighty says:",
    "verse_7": "“Big mountain, you are no problem. You will become flat ground in front of Zerubbabel. Then he will bring out the last and biggest stone of my house. The people will shout, ‘God bless it! God bless it!’ ” ’",
    "verse_8": "Then the Lord's message came to me, Zechariah. He said,",
    "verse_9": "‘Zerubbabel has put down the first stone of my house. He will also finish it.’ Then you will know that the Lord Almighty has sent me to you.",
    "verse_10": "Everyone should know that the day of small things is important. Men will see Zerubbabel. Then they will sing and they will be happy. They will see him with a line in his hand to measure the walls. The Lord sees everything in the whole earth. (The seven lights are the seven eyes of the Lord.)",
    "verse_11": "Then I said to the angel, ‘What are these two olive trees that stand on the right and on the left of the lampstand?’",
    "verse_12": "A second time I spoke to the angel, ‘What are these two branches of the olive trees? They are next to the gold pipes and oil comes from those pipes.’",
    "verse_13": "The angel replied, ‘Do you not know what these olive trees mean?’ ‘No, my lord,’ I said.",
    "verse_14": "So the angel said, ‘These are the two men that the Lord of all the earth has chosen to be his servants.’"
  },
  "chapter_5": {
    "verse_1": "Again, I looked and I saw a large paper. It was moving through the air. There were many words on the paper.",
    "verse_2": "The angel said to me, ‘What do you see?’ And I answered, ‘I see a paper that is flying through the air. It is 30 feet long and 15 feet wide.’",
    "verse_3": "Then the angel said to me, ‘The words on the paper tell about bad events for the whole earth. This will be in future years. On one side of the paper, it says that a man must not rob anyone. If he does, people will send him away from his own country. On the other side of the paper, it says that a man must not speak false words. If he does, people will send him away from his own country.",
    "verse_4": "The Lord Almighty says, “I will cause bad things to happen in the house of the man that robs anyone. I will cause bad things to happen in the house of the man that speaks false words. It is as if the words on the paper will destroy the houses of those bad people.” ’",
    "verse_5": "Then the angel that talked to me came near to me. He said, ‘Look. And see the thing that has just appeared.’",
    "verse_6": "I said, ‘What is it?’ He said, ‘It is a basket that people measure with.’ Then he said, ‘It is the sin of all the people in this country.’",
    "verse_7": "He lifted the heavy metal lid and there was a woman. She was sitting in the basket!",
    "verse_8": "The angel said, ‘This is sin.’ He pushed her into the basket again and he put the heavy metal lid on top of the basket.",
    "verse_9": "Then I looked up and I saw two women. They flew towards me with strong wings. The wind carried them as the wind carries large birds. They lifted the basket between the earth and the sky.",
    "verse_10": "Then I said to the angel that talked with me, ‘Where will these women take the basket?’",
    "verse_11": "The angel said to me, ‘They will take the basket to the country called Babylon. They will build a house for it there. When the house is ready, they will put the basket inside the house. They will put it where people can see it.’"
  },
  "chapter_6": {
    "verse_1": "Again I looked up and I saw four chariots! They came out from between two mountains and the mountains were mountains of shining metal!",
    "verse_2": "The first chariot had red horses and the second chariot had black horses.",
    "verse_3": "The third chariot had white horses and the fourth chariot had grey horses. All the horses were strong.",
    "verse_4": "Then I spoke to the angel that talked to me. I asked him, ‘What are these chariots, my lord?’",
    "verse_5": "The angel answered me, ‘These are the four spirits of heaven. They have come from the Lord of the whole world.",
    "verse_6": "The chariot with the black horses goes towards the north country. The chariot with the white horses goes after them. The chariot with the grey horses goes towards the south country.’",
    "verse_7": "When the strong horses came out, they were in a hurry to leave. The angel said, ‘Go through all the earth.’ So the horses went through all the earth.",
    "verse_8": "Then the Lord told me, ‘The chariot that goes to the north country has caused my Spirit to rest in the north country. I am now no longer angry about the north country.’",
    "verse_9": "The Lord spoke to me.",
    "verse_10": "‘Three men have arrived from Babylon,’ he said. ‘Their names are Heldai, Tobijah and Jedaiah. Take the gold that they have brought with them. On the same day, take the gold to the house of Josiah, the son of Zephaniah.",
    "verse_11": "Take the gold and other valuable metal and make a crown. Put it on the head of Joshua the most important priest. He is the son of Jehozadak.",
    "verse_12": "Say to Joshua, “The Lord Almighty says, ‘I have chosen a man. His name is the Branch. He will be a great man and he will build the house of the Lord.",
    "verse_13": "It is he who will build the house of the Lord. He will sit on his special high seat and he will rule all the people. He will be a priest on the seat of a king. This one man will be priest and king.’ ”",
    "verse_14": "They will put the crown in the house of the Lord. This is to remember Heldai, Tobijah, Jedaiah and Hen the son of Zephaniah. This is because they brought the gold from Babylon.",
    "verse_15": "People will come a long way and they will help to build the house of the Lord. Then you will know that the Lord Almighty has sent me to you. All this will happen if you completely obey the Lord your God.’"
  },
  "chapter_7": {
    "verse_1": "The Lord spoke to Zechariah when Darius had been king for four years. It was the fourth day of the ninth month. The name of the month was Kislev.",
    "verse_2": "Then the people in Bethel sent Sharezer and Regem-Melech and their men to Jerusalem. They came to ask the Lord to help them.",
    "verse_3": "They came to the house of the Lord Almighty to speak to the priests and to the prophets. They asked, ‘Should we cry and not eat our food in the fifth month? We have done this for many years.’",
    "verse_4": "The Lord Almighty spoke to me.",
    "verse_5": "He said, ‘Say this to all the people in this country and to the priests: “You lived in Babylon for many years. You ate no food and you were sad in the fifth month and in the seventh month. But you did not do this for me.",
    "verse_6": "You ate and you drank. But you ate and you drank for yourselves.",
    "verse_7": "These are the words that I, the Lord, spoke by my prophets in past years. At that time, the people in Jerusalem lived without trouble. Many rich people lived in Jerusalem. People in the Negev region in the south and in the low hills in the west also lived safely.” ’",
    "verse_8": "The Lord spoke again to Zechariah. He said,",
    "verse_9": "‘The Lord Almighty has said, “Be sure that you are fair to all people. Be kind to each other.",
    "verse_10": "Do not cheat widows or children who have no family. Do not cheat foreigners or poor people. Do not think secretly of ways to hurt each other.”",
    "verse_11": "But the people would not listen and they turned away. They put their hands over their ears, because they did not want to hear.",
    "verse_12": "They decided that they would not listen to God's rules or to the messages from the prophets. But the Lord Almighty had sent those messages by His Spirit. So I, the Lord Almighty, was very angry.",
    "verse_13": "When I spoke to them, they did not listen. So when they prayed to me, I did not listen to them, says the Lord Almighty.",
    "verse_14": "As a storm takes things away, I took my people away to strange countries. The country that they left became an empty country. Nobody lived in it. That is how they made the good country an empty country.’"
  },
  "chapter_8": {
    "verse_1": "The Lord Almighty gave this message to Zechariah.",
    "verse_2": "‘I have wanted to help Jerusalem because I love its people very much. My love causes me to be very angry with the enemies of Jerusalem,’ says the Lord Almighty.",
    "verse_3": "‘Jerusalem is the city that I have chosen. I will return there and I will live there. Then Jerusalem will be called the city that obeys God. And the mountain of the Lord Almighty will be called the mountain that God has chosen.’",
    "verse_4": "The Lord Almighty says, ‘Old men and old women will sit in the streets of Jerusalem again. Each will have a stick in his hands because he is so old.",
    "verse_5": "Many boys and girls will play in the streets of the city again.’",
    "verse_6": "‘This may seem impossible to the few people that remain,’ says the Lord Almighty. ‘But nothing is impossible to me,’ says the Lord Almighty.",
    "verse_7": "‘I will bring my people back from the east country and from the west country,’ says the Lord Almighty.",
    "verse_8": "‘I will bring them back to live in Jerusalem. They will be my people and I will be their God. I will do for them what I promised to do.’",
    "verse_9": "The Lord Almighty says, ‘Be strong, you people who now hear these words from the mouths of the prophets. The prophets spoke the same words when you prepared the ground for the temple of the Lord Almighty. Now be strong and continue to build.",
    "verse_10": "Before that time, there was not enough money to pay for work that men or animals did. No man was safe from the enemy because I made all men angry with each other.’",
    "verse_11": "‘But now it is different. I will not be angry with the few people that have returned,’ says the Lord Almighty.",
    "verse_12": "‘The seeds and the plants will grow well. The trees will give fruit. There will be water from the skies. I will bless the few people that will return.",
    "verse_13": "In past years, people from other countries have said bad things against you, Judah and Israel. But now I will help you. You will bless many people. Do not be afraid. Be strong.’",
    "verse_14": "The Lord Almighty says this: ‘When your parents and their parents made me angry, I decided to punish them.’ ‘I have also punished you,’ says the Lord Almighty.",
    "verse_15": "‘Do not be afraid. I have now decided to do good things to Jerusalem and to the people in Judah again.",
    "verse_16": "These are the things that you should do. Speak true words to each other. Leaders, be fair to all people.",
    "verse_17": "Do not think to do bad things against other people. Do not use my name to promise things and then not do those things. All these things make me very angry.’",
    "verse_18": "Again Zechariah the prophet heard this message from the Lord Almighty.",
    "verse_19": "‘On special days in the year you eat no food. Those days are in the fourth, fifth, seventh and tenth months. But I want you to enjoy those days,’ says the Lord Almighty. ‘I want the people in Judah to be happy. So speak true words and live quiet lives.’",
    "verse_20": "‘People that live in many countries will come to Jerusalem,’ says the Lord Almighty.",
    "verse_21": "‘The people from one city will go to the people in another city. They will say, “Come with us to worship the Lord Almighty. Come and ask the Lord to help us.”",
    "verse_22": "People from many powerful nations will worship the Lord Almighty in Jerusalem. They will ask the Lord to help them.’",
    "verse_23": "‘Then, ten men from foreign countries will hold the coat of one Jew,’ says the Lord Almighty. ‘They will say, “People have told us that the Lord is with you. So we want to go with you.” ’"
  },
  "chapter_9": {
    "verse_1": "The Lord speaks against the land of Hadrach, and against the city of Damascus. The Lord watches all men and all the groups of people in Israel.",
    "verse_2": "The Lord speaks against the country called Hamath. (It is next to the country called Hadrach.) The people in Tyre and Sidon cities are very wise. But the Lord also speaks against them.",
    "verse_3": "Tyre's people have built strong walls to keep enemies out. They have swept up rich metals like dirt. They have swept up gold like dirt in the streets.",
    "verse_4": "The Lord will take away all the things that Tyre's people have. And he will remove their ships from the sea. Fire will burn every part of the city.",
    "verse_5": "The people in Ashkelon city will see it and they will be afraid. The people in Gaza city will see it and they will be afraid. The things that the people in Ekron city hope for will not happen. The king of Gaza will die and there will be no people in Ashkelon any longer.",
    "verse_6": "Foreign people will live in Ashdod city. I will show the Philistines that they are not clever. They are not as clever as they believe.",
    "verse_7": "I will take the blood from their mouths. I will take the food from their teeth, because it is bad food. Those that remain will still be my people. They will become leaders in Judah. Ekron will be like a part of Judah, as the Jebusites were.",
    "verse_8": "Then I will keep my house safe against my enemies. No army will ever again beat my people, because I am watching them.",
    "verse_9": "Sing loudly, people in Zion. Shout, people in Jerusalem. Look! Your king comes to you. He will save you because he does everything well. But he is quiet and he is riding on a donkey. He will ride on a young animal. Its mother is a donkey.",
    "verse_10": "I will take away the chariots from Ephraim, and the horses of war from Jerusalem. The bows of war will be broken. He will speak to all the countries and wars will finish. He will rule from sea to sea. He will rule from the river Euphrates to the ends of the earth.",
    "verse_11": "But I made a promise to you. I made that promise true with blood. I will free your people that are in a prison, in deep dark holes without water.",
    "verse_12": "All you people who hoped to see your own country again, return to Jerusalem. I tell you this now: I will give back to you twice as much as you have lost.",
    "verse_13": "I will use Judah and Israel to attack my enemies. I will use you, men from Zion, to attack the men from Greece. I will make you like the long metal knife of a soldier.",
    "verse_14": "Then the Lord will appear above his people. His arrows will be as fast as lightning in the sky. The Lord God will make a loud sound with a trumpet. He will march in a storm from the south to attack.",
    "verse_15": "And the Lord Almighty will help his people. They will throw great stones at their enemies. When they go to war, they will shout loudly, like men who have drunk too much wine. They will be as full of joy as the priest's bowl is full of blood, when he pours it on the altar.",
    "verse_16": "On that day, the Lord will save them. They are his people. They will shine in his country like beautiful stones that shine in a crown.",
    "verse_17": "The people will be beautiful and good. The young people will become strong when they eat good bread. The young women will become strong when they drink new wine."
  },
  "chapter_10": {
    "verse_1": "Ask the Lord for rain in spring. It is the Lord who makes the clouds and the storms. He gives the rain to men. He gives the plants of the field to everyone.",
    "verse_2": "People ask idols for help, but the idols do not speak true words. Some people explain what a dream means. But they do not speak true words. The help that they give is not good. So the people move from place to place like sheep. They are not safe. They have no leaders.",
    "verse_3": "‘I am angry with the leaders. I will cause them to be sorry. Judah's people are mine,’ says the Lord Almighty. ‘I will watch over them. I will make them as strong as horses that are ready for war.",
    "verse_4": "From Judah's descendants will come a strong leader. He is like a strong stone at the corner of a building. He is like a strong peg in a wall. He is like a bow that is ready to shoot arrows. Every strong ruler will come from Judah's descendants.",
    "verse_5": "Together they will be like brave soldiers who march through the mud in the streets of their enemies. The Lord is with them and they will fight their enemies. They will pull down the soldiers from their horses.",
    "verse_6": "I will make Judah's people strong, and I will make Israel's people become free. I will bring them back to me, because I am sorry for them. I am their God, and I will answer them. It will be as if I had never turned away from them.",
    "verse_7": "Israel's people will become like strong men. They will be as happy as men that drink wine. Their children will see their happy fathers and so the children will be happy. They will sing to the Lord.",
    "verse_8": "I will cause my people to come to me and I will bring them all together. I will buy them and I will make them free people. And there will be as many people as there were before.",
    "verse_9": "I will send them to foreign countries among foreign people. But, in these far countries, they will remember me. They and their children will not die. They will return to Jerusalem.",
    "verse_10": "I will bring my people back from Egypt, and I will bring them here together from Assyria. I will bring them to Gilead and to Lebanon. There will not be enough room for them all.",
    "verse_11": "And he will come to the difficult sea. But it will be no trouble to him. He will stop the waves in the sea. He will make the river Nile dry. Proud Assyria will have nothing to be proud about and the power of Egypt's people will finish.’",
    "verse_12": "‘I will make my people strong. They will obey me because they love my name.’"
  },
  "chapter_11": {
    "verse_1": "Open your gates, Lebanon, so that the fires can burn down your cedar trees.",
    "verse_2": "Cry aloud, cypress tree, because the cedar tree has fallen. Enemies have cut down the tall and beautiful trees. Cry aloud, oak trees in Bashan, because they have cut down the thick forest.",
    "verse_3": "Listen to the shepherds! They are crying because enemies have destroyed their fields. Listen to the noise of the lions! They are roaring because the trees beside the Jordan River are no longer there.",
    "verse_4": "This is what the Lord said to me, Zechariah. ‘My people are like sheep. There will be a time when men will buy them. And then they will kill them. But feed them until that time.",
    "verse_5": "Those men who buy the sheep will kill them. Nobody will punish them. They will sell them. And they will say, “Thank you Lord, because I am a rich man.” Their own shepherds do not give the sheep any help.’",
    "verse_6": "The Lord says, ‘The people in this country were my people, but they are not my people now. I will not go on being kind to them. I myself will give them to their enemies and to foreign kings. The foreign kings will do very bad things to the country, but I will not come to help.’",
    "verse_7": "So I was a good shepherd to the sheep that men would soon kill. I took special care of the weakest sheep. Then I took two sticks. And I called one stick ‘Grace’ and I called the other stick ‘Together’. I fed the sheep.",
    "verse_8": "In one month, I sent away three shepherds. They did not like me and I was not patient with them.",
    "verse_9": "I said to the sheep, ‘I will not be your shepherd and you will die. The sheep that do not die will eat each other.’",
    "verse_10": "I took ‘Grace’ which was my first stick. I broke it into two pieces. The Lord's promise to his people finished.",
    "verse_11": "On the day that the Lord's promise finished, the weak sheep watched me. They knew that it was the Lord's message.",
    "verse_12": "I said to them, ‘You may think that I should have some money for my work. If you do think that, pay me my money. If you do not want to pay me, keep it.’ So they paid me 30 silver coins.",
    "verse_13": "The Lord said to me, ‘Throw the 30 silver coins to the man who makes pots in the house of the Lord.’ They thought that I was not worth very much! I took the 30 coins. And I threw them to the man who makes pots. He makes them for the house of the Lord.",
    "verse_14": "Then I broke the second stick called ‘Together’. I made the kingdom of Judah separate from the kingdom of Israel.",
    "verse_15": "Then the Lord said to me, Zechariah, ‘Take again the tools of a useless shepherd.",
    "verse_16": "I have chosen a man to watch the sheep. He will not help the sheep that are dying. He will not look for the sheep that have gone away. He will not help the sick sheep or feed the strong sheep. He will eat the meat of the fat sheep. He will tear off their feet to get all the meat.",
    "verse_17": "Bad things will happen to the bad shepherd who leaves his sheep. His enemy's knife will cut his arm and his right eye. His arm will become like a dry stick. And his right eye will no longer be able to see anything.’"
  },
  "chapter_12": {
    "verse_1": "This is the Lord's message about Israel. The Lord made the skies and the whole wide earth. He makes men and women.",
    "verse_2": "‘I will frighten the enemies that live round Jerusalem. I will frighten them so much that they will run. They will run as fast as they can from Jerusalem and from Judah.",
    "verse_3": "There will be a time when all the countries of the earth will be ready to attack Jerusalem. Then I will make Jerusalem like a heavy rock that nobody can move. All those who try to lift it will hurt themselves very badly.",
    "verse_4": "On that day,’ says the Lord, ‘I will make every horse very afraid. I will make all the men that ride them crazy. I want to help Judah's people. And so, I will not let the horses of the enemy see any longer.",
    "verse_5": "Then the leaders of Judah will say to themselves, “The Lord Almighty, their God, makes the people in Jerusalem strong. And they will help us.”",
    "verse_6": "On that day, I will make the leaders of Judah like fire in a forest. I will make them like fire among wheat that the farmer has cut. They will kill all the people from round Jerusalem, but the people in Jerusalem will be safe.",
    "verse_7": "The Lord will save the homes of the people from Judah first. So David's family and the people who live in Jerusalem will not be greater than the people from Judah.",
    "verse_8": "On that day, the Lord will save the people who live in Jerusalem. Even sick people will be as strong as King David was. The family of David will lead the people from Jerusalem like the angel of the Lord. God himself will go before them.",
    "verse_9": "On that day, I will destroy all the countries that fight against Israel.",
    "verse_10": "I will cause the family of David and the people in Jerusalem to think seriously about me. Then they will know that I am kind to them. And they will want to pray to me. They will look at me whom they pierced (made holes in). They will weep about him as those that weep after the death of their only son. They will cry aloud as if their only son was dead.",
    "verse_11": "On that day, people will weep loudly in Jerusalem. It will be like when they were weeping about Hadad-Rimmon in the fields of Megiddo.",
    "verse_12": "All the people will weep. Each family will weep by itself. The family of King David will weep by itself. And their wives will weep by themselves. The family of Nathan will weep by itself. And their wives will weep by themselves.",
    "verse_13": "The family of Levi will weep by itself. And their wives will weep by themselves. The family of Shimei will weep by itself. And their wives will weep by themselves.",
    "verse_14": "And all the families that have not died will weep by themselves. And their wives will weep by themselves.’"
  },
  "chapter_13": {
    "verse_1": "‘On that day, water will start to pour from a fountain for King David's descendants and Jerusalem's people. It will make them clean from their sins and the dirty things that they have done.’",
    "verse_2": "The Lord Almighty says, ‘On that day, I will remove the names of false gods from the country. Everyone will forget them. I will remove all the false prophets. And I will remove the bad spirit that is not holy.",
    "verse_3": "And if anyone appears as a prophet again, his father and his mother will say to him, “You must die. You do not speak true words. The Lord has not spoken to you.” Then they will kill him.",
    "verse_4": "On that day, every prophet will be ashamed that he was ever a prophet. He will not put on the clothes of a prophet that they make from hair. Then people will not know that he is a prophet.",
    "verse_5": "He will say, “I am not a prophet. I am a farmer. From the time that I was a boy, I have worked on the land.”",
    "verse_6": "If someone asks him, “Who cut your body?” he will answer, “My friends cut me when I was at their house.” ’",
    "verse_7": "‘Attack my shepherd with a sharp knife. Attack the man that is next to me,’ says the Lord Almighty. ‘Kill the shepherd and then the sheep will run away. Then I will attack the young sheep.",
    "verse_8": "In the whole country,’ says the Lord, ‘two thirds of the people will die. But one third will still be living there.",
    "verse_9": "I will bring these people through fire. As men clean silver in the fire, so I will clean them. As men test gold in the fire, so I will test them. They will speak my name and I will answer them. I will say, “They are my people.” They will say, “The Lord is our God.” ’"
  },
  "chapter_14": {
    "verse_1": "There will be a day when your enemies will take away everything. They will take away everything that is yours. They will each have some of your things.",
    "verse_2": "I will bring soldiers from all countries to fight against Jerusalem. They will go into the city and they will rob the houses. They will have sex with the women. They will lead away half the people to other countries. They will let the other half stay in Jerusalem.",
    "verse_3": "Then the Lord will go out. And he will fight against the people from those countries as in past years.",
    "verse_4": "On that day, the Lord's feet will stand on the Mount of Olives. This mountain is east of Jerusalem. It will break in two from east to west and it will make a wide valley. Half of the mountain will move north and half of the mountain will move south.",
    "verse_5": "In the time of Uzziah, king of Judah, you ran away when the earth moved. You will do this again. Then the Lord will come. And all those who are holy will come with him.",
    "verse_6": "On that day, it will not be light in some places and dark in other places.",
    "verse_7": "It will be a day like no other day. There will be no night. When it is evening, there will still be light. Only the Lord himself will know that day.",
    "verse_8": "On that day, water will come out from Jerusalem. Half of this water will go towards the sea in the east. Half of this water will go towards the sea in the west. This will go on during summer and winter.",
    "verse_9": "The Lord will be king over the whole earth. On that day, there will be only one Lord and he will have only one name.",
    "verse_10": "All the land, from Geba to Rimmon, south of Jerusalem, will become flat. But Jerusalem will rise and it will be high in its place. The city will be from the Gate of Benjamin to the Corner Gate and to the High Building of Hananel. The place where the servants of the king make his wine will be in it too.",
    "verse_11": "Jerusalem will be safe. People will live there. Nobody will destroy Jerusalem ever again.",
    "verse_12": "The Lord will make the people sick that fought against Jerusalem. Their bodies will become bad as they stand on their feet. Their eyes will become bad and they will fall out. And their tongues will become bad in their mouths.",
    "verse_13": "On that day, the Lord will make men so afraid that each man will attack the man next to him.",
    "verse_14": "Judah also will go to Jerusalem and they will fight. They will take every good thing from all the countries. There will be a lot of expensive metals and many rich clothes.",
    "verse_15": "The horses and all the other animals will be sick. And they will die as the soldiers died.",
    "verse_16": "Some of the soldiers from the countries that attacked Jerusalem will not die. They will go to Jerusalem year after year to worship the King, the Lord Almighty. They will worship him at the Feast of Huts.",
    "verse_17": "All the people on the earth will have to go to Jerusalem to worship the King, the Lord Almighty. If any people on the earth do not go, they will have no rain.",
    "verse_18": "If the people from Egypt do not go to Jerusalem to worship the Lord, they will have no rain. And the Lord will make them sick. If the people from other countries will not go to Jerusalem, the Lord will make them sick. They will die.",
    "verse_19": "This will happen to the people from Egypt. This will happen to the people from all the countries that do not go up to Jerusalem at that time.",
    "verse_20": "On that day, men will write the words, ‘This is for the Lord’ on the bells of the horses. The pots that anyone uses to cook with in the house of the Lord will be special. They will be as special as the dishes in front of the altar.",
    "verse_21": "Every pot in Jerusalem and Judah will be for the Lord Almighty. All the people who come to offer animals to the Lord will cook in those pots. On that day, nobody who sells things will come into the house of the Lord Almighty."
  }
};
