var zephaniah_data = {
  "chapter_1": {
    "verse_1": "This is the Lord's message, which he gave to Zephaniah, Cushi's son. Cushi's father was Gedaliah. Gedaliah's father was Amariah, and Amariah's father was Hezekiah. The Lord gave this message to Zephaniah when Josiah was king. Josiah was the son of Amon, who was the king of Judah.",
    "verse_2": "‘It is the Lord who is speaking now. I will remove everything from the ground.",
    "verse_3": "I will remove men and animals. I will remove the birds that fly in the air. I will also remove the fish that live in the sea. I will remove all the bad people. Bad people cause trouble for other people. Yes, I will remove all the people from the ground. It is the Lord who is speaking.",
    "verse_4": "I will destroy Judah. I will remove all the people who live in Jerusalem. I will remove all those who believe in the false god Baal. I will remove Baal's priests.",
    "verse_5": "Some people stand on the roof tops to worship the sun, the moon and the stars. I will remove those people. Some people say that they love me. But they say also that they love Malcam (a false god). So I will remove them, too.’",
    "verse_6": "‘I will remove those who have turned away from the Lord. I will also remove those who decide things without the Lord.",
    "verse_7": "Be quiet! The Lord God is here. It will soon be the day of the Lord. The Lord has made his sacrifice ready. He has made the people ready who will give the sacrifice to him.’",
    "verse_8": "‘When it is time for the Lord's sacrifice, I will punish the rulers and the king's sons. I will punish everyone who wears clothes like foreign people do.’",
    "verse_9": "‘I will also punish the people who rush into other people's houses. They do that because they want to rob those people. On that same day, I will also punish other robbers. Those people fill their masters' houses with the things that they take.’",
    "verse_10": "The Lord says, ‘On that day you will hear the noise of people who are shouting from one gate of the city. It is the gate called the Fish Gate. And there will be sad sounds from the next gate. There will be loud noises from the hills.",
    "verse_11": "Shout out, you who live near Jerusalem's market! Weep! The Lord will remove the traders from your town. Some people have lots of money there. But all those people will be dead then.’",
    "verse_12": "‘At that time, I will look in all Jerusalem's dark corners. I will take lights with me. I will find the drunks and I will punish them. These people say in their minds, “The Lord will do neither good things nor bad things to us.”",
    "verse_13": "So I will take away from them everything that they have. I will take away their houses too. They will build houses, but they will never live in them. They will plant plants to get grapes. But they will never have wine from them.’",
    "verse_14": "The time for the great day of the Lord is coming very soon. It will happen quickly. Strong men will weep when they hear the noise of it.",
    "verse_15": "The Lord will be very angry at that time. It will be a time when there will be trouble. On that day, he will destroy everything bad. It will be very dark. At that time, there will be thick dark clouds.",
    "verse_16": "At that time, people will make a noise with trumpets. They will shout when they go to fight in a war. In the fight, they will try to destroy the strong walls of cities. And they will try to destroy the strong high parts of the walls.",
    "verse_17": "I will cause trouble for people. So they will walk like people who cannot see. This is because they have not obeyed the Lord. Their blood will fall to the ground. Yes, they will fall to the ground and they will die. After that, they will be nothing.",
    "verse_18": "Their money will not save them, on the day when the Lord is angry. He watches. And he is angry when his people love other gods. So he will send fire on the earth. Yes, he will quickly kill all the people who live in Judah."
  },
  "chapter_2": {
    "verse_1": "Come together! Yes, you people, come together and think. You do not know how to be ashamed!",
    "verse_4": "Then, the people who have lived in Gaza city and Ashkelon city will not be there. Enemies will also send away the people in Ashdod city at midday. And those enemies will destroy Ekron city.",
    "verse_5": "Terrible trouble will come to you people who came from Crete, you people who live beside the sea! The Lord has said this against you: I will kill all you Philistines who live in the land of Canaan! You will all die. So nobody will live there.",
    "verse_6": "By the sea, there will be houses for people who feed sheep. There will be safe places for their sheep.",
    "verse_7": "Those people in Judah who love God will live there, by the sea. They will have food there. They will lie down to sleep in Ashkelon city's houses. The Lord, their God, will be with them. He will stop their troubles.",
    "verse_8": "The Lord of all his armies says, ‘I have heard the cruel people in the countries called Moab and Ammon. They laugh about you and they say cruel things about you, my people. They have thought that they were greater than you. They have come against you.’",
    "verse_9": "The Lord Almighty, Israel's God, says, ‘You can be sure that I live. In the same way, you can also be sure that my people will take everything for themselves. God will destroy Moab as he destroyed Sodom. He will destroy Ammon as he destroyed Gomorrah. After this, the ground will have lots of salt on it. Weeds will grow there. Nobody will build anything there again. My people who are still alive will take for themselves the Ammonites' things and the Moabites' things.’",
    "verse_10": "That will happen to all proud people. The proud people said cruel words to God's people. The cruel people thought that they were greater than the people of the Lord Almighty.",
    "verse_11": "The Lord will make them afraid. He will destroy all the false gods. People will worship him instead. Every person, in his own place, will worship God. They will also worship him in the places where the people now believe in false gods.",
    "verse_12": "‘I will also punish you people in the country called Ethiopia. Other people will kill you with a big knife,’ the Lord says.",
    "verse_13": "The Lord will go against the north. There, he will destroy the country called Assyria. He will also destroy Nineveh city. That place will become as dry as a desert.",
    "verse_14": "Sheep will lie down there. All the wild animals of that place will live together there. Vultures and owls will rest on top of the high, thin parts of the buildings. They will sing in the windows. Bits of doors will lie on the ground. The Lord will tear down all the things in the houses that they have made from valuable wood.",
    "verse_15": "All this will happen to that city, the proud city. That city's people said in their minds, ‘Here we are. We are greater than all the other people.’ But then, other people will destroy their city! Only bits of it will still be there. Then wild animals will come and they will lie down in it. People will see this. So any people who pass by the city will make noises with their lips. And they will hold their fists up. In this way, they will show that they think bad things about the city."
  },
  "chapter_3": {
    "verse_1": "It will be very bad for the city! It is like something that is dirty. Its people will not obey me. They like to fight weak people. They also like to do bad things.",
    "verse_2": "They do not listen to anyone's voice. Nobody can warn them that they are doing wrong things. They do not trust in the Lord. They do not come near to their God.",
    "verse_3": "The rulers of the city make a very loud noise with their voices like big wild animals. Its judges are like hungry wolves. They are like wolves that have even eaten all an animal's bones before morning.",
    "verse_4": "Its prophets do not know what to think. People cannot trust them. Its priests have done wrong things, even in God's holy house. They have also made changes to God's rules. They have made changes that they want.",
    "verse_5": "But the Lord is among all the people in the city. He will do what is right. He is always the honest judge. He never fails. But the bad people do not know how to be ashamed.",
    "verse_6": "‘I have destroyed nations,’ the Lord says. ‘There is nobody in their strong towers now. I have made their streets empty, so no people are there. I have destroyed their cities. So nobody lives in them now.",
    "verse_7": "I said, “Now people in the city will respect me! Now they will agree when people warn them.” The people would have been safe if they had accepted it. Then I would not have to destroy them. But it did not happen. I had to punish them. Still, the people got up early to do bad things.",
    "verse_8": "So wait for me, I will stand up and I will punish the nations. I have decided to bring together the nations and the people that kings rule over. Then I will punish them very, very much. They will see how angry I am. They will see it because, on that day, I will burn all the earth.’ That is what the Lord says.",
    "verse_9": "‘Then I will give to people lips that I have made pure. With those lips, they will call me Lord. And then, all the people will agree to work together for me.’",
    "verse_10": "‘Some people live a long way beyond the rivers of Cush. Yes, my people who pray went away to many other countries. They will return and they will carry their gifts to me.",
    "verse_11": "At that time, you will not have to be ashamed of the wrong things that you have done against me. But I will take away those who do not see anything wrong in themselves. Those people will not call each other “the people who live on God's holy mountain”.",
    "verse_12": "But I will let the poor people remain there. These are the people who have had bad times. These are the people who will trust me. And they will call me Lord.",
    "verse_13": "I will let those people stay there. They will not do any bad things. They will only say things that are true. They will say honest things. They will eat well and they will sleep well. Nobody will make them afraid.’",
    "verse_14": "Sing, you people in Zion. You are my own people, like my own daughter. Shout, you people in Israel! Be very, very happy, my people in Jerusalem!",
    "verse_15": "The Lord has not punished you as he would have done. He has sent your enemy away. I, the King of Israel, am with you! The bad times have gone. They will not happen again!",
    "verse_16": "On that special day, this will be my message for Jerusalem. ‘Do not be afraid now! Do not be weak now!",
    "verse_17": "The Lord, your God, is with you. He is strong. He will save you. He will be very happy about you! He will quietly love you. He will sing, because he is so happy about you!",
    "verse_18": "I will bring together those people among you who want to meet together again. You want to meet again to pray. And you want to meet again to praise God. You have had enough cruel words from your enemies.",
    "verse_19": "Look! At that time, I will punish all those people who hurt you. I will save those who cannot walk well. I will bring back the people that the enemy has sent away. I will cause people in every country to know about you. I will cause them to praise you.",
    "verse_20": "At that time, I will bring you back to your home. I will bring you back together. I will give you a good name among all the people on the earth. That is what I will do. I will stop your troubles. And you will see it happen.’ That is what the Lord says."
  }
};
