create table public.user_settings (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  theme text not null default 'system'::text,
  language text not null default 'ta'::text,
  english_text_color text not null default 'default'::text,
  images boolean not null default true,
  short_summary boolean not null default true,
  bible_reading boolean not null default true,
  verse_heading boolean not null default true,
  author_details boolean not null default true,
  memory_verse boolean not null default true,
  bookmark boolean not null default true,
  notes_feature boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint user_settings_pkey primary key (id),
  constraint user_settings_user_id_key unique (user_id),
  constraint user_settings_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;